/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.DAOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import negocio.NegocioException;

/**
 *
 * @author Marnei
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     * @throws gui.GuiException
     */
    public JanelaPrincipal() throws GuiException, NegocioException, DAOException {
        controlador = new LeilaoControlador();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuBancoDados = new javax.swing.JMenu();
        jMenuItemBDConfiguracoes = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBDCriar = new javax.swing.JMenuItem();
        jMenuItemBDPopular = new javax.swing.JMenuItem();
        jMenuItemBdRecriar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leilão");
        setName("framePrincipal"); // NOI18N

        jMenu1.setText("Arquivo");

        jMenuItemLogin.setText("Login...");
        jMenu1.add(jMenuItemLogin);
        jMenu1.add(jSeparator1);

        jMenuBancoDados.setText("Banco de dados");

        jMenuItemBDConfiguracoes.setText("Configurações...");
        jMenuItemBDConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDConfiguracoesActionPerformed(evt);
            }
        });
        jMenuBancoDados.add(jMenuItemBDConfiguracoes);
        jMenuBancoDados.add(jSeparator3);

        jMenuItemBDCriar.setText("Criar banco da dados");
        jMenuItemBDCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDCriarActionPerformed(evt);
            }
        });
        jMenuBancoDados.add(jMenuItemBDCriar);

        jMenuItemBDPopular.setText("Popular banco de dados");
        jMenuBancoDados.add(jMenuItemBDPopular);

        jMenuItemBdRecriar.setText("Recriar banco da dados");
        jMenuBancoDados.add(jMenuItemBdRecriar);

        jMenu1.add(jMenuBancoDados);
        jMenu1.add(jSeparator2);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemBDConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDConfiguracoesActionPerformed
        try {
	    try {
		new JanelaBdConfiguracoes().setVisible(true);
	    } catch (NegocioException ex) {
		Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
	    } catch (DAOException ex) {
		Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
	    }
        } catch (GuiException ex) {
            Logger.getLogger(JanelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
	    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao carregar a tela", JOptionPane.ERROR_MESSAGE);  
        }
    }//GEN-LAST:event_jMenuItemBDConfiguracoesActionPerformed

    private void jMenuItemBDCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDCriarActionPerformed
        //controlador.criarBD();
    }//GEN-LAST:event_jMenuItemBDCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaPrincipal().setVisible(true);
                } catch(GuiException | NegocioException | DAOException ex) {
                    Logger.getLogger(JanelaBdConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro fatal", JOptionPane.ERROR_MESSAGE);  
		}
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuBancoDados;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBDConfiguracoes;
    private javax.swing.JMenuItem jMenuItemBDCriar;
    private javax.swing.JMenuItem jMenuItemBDPopular;
    private javax.swing.JMenuItem jMenuItemBdRecriar;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
    private LeilaoControlador controlador;
}
