/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.DAOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import negocio.pojos.Categoria;

/**
 *
 * @author Marnei
 */
public class JDialogCategorias extends javax.swing.JDialog {

	private LeilaoControlador controlador;
	private JFramePrincipal jFramePrincipal;

	/**
	 * Creates new form JDialogCategorias
	 */
	public JDialogCategorias(java.awt.Frame parent, boolean modal, LeilaoControlador c) throws DAOException {
		super(parent, modal);
		jFramePrincipal = (JFramePrincipal) parent;
		controlador = c;
		initComponents();
		preencher();
	}

	private void preencher() throws DAOException {
		DefaultListModel listaCategorias = new DefaultListModel();
		for (Categoria item : controlador.fachada.listarCategorias(null)) {
			listaCategorias.addElement(item.getDescricao());

		}
		jListCategorias.setModel(listaCategorias);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuCategorias = new javax.swing.JPopupMenu();
        jMenuItemAdicionar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCategorias = new javax.swing.JList();

        jPopupMenuCategorias.setComponentPopupMenu(jPopupMenuCategorias);

        jMenuItemAdicionar.setText("Adicionar...");
        jMenuItemAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarActionPerformed(evt);
            }
        });
        jPopupMenuCategorias.add(jMenuItemAdicionar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorias");

        jListCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListCategorias.setToolTipText("");
        jListCategorias.setComponentPopupMenu(jPopupMenuCategorias);
        jListCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCategoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListCategorias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(416, 249));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarActionPerformed
		JDialogCategoria jDialogCategoria = new JDialogCategoria(jFramePrincipal, true, controlador, null);
		jDialogCategoria.setVisible(true);
		try {
			preencher();
		} catch (DAOException ex) {

		}
    }//GEN-LAST:event_jMenuItemAdicionarActionPerformed

    private void jListCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCategoriasMouseClicked
		if (evt.getClickCount() == 2) {
			try {
				//int index = jListCategorias.locationToIndex(evt.getPoint());
				Categoria categoriaSelecionada = controlador.listarCategorias(new Categoria(null, jListCategorias.getSelectedValue().toString(), null)).get(0);
				JDialogCategoria jDialogCategoria = new JDialogCategoria(jFramePrincipal, true, controlador, categoriaSelecionada);
				jDialogCategoria.setVisible(true);
				//System.out.println("index: " + index);
			} catch (DAOException ex) {
				Logger.getLogger(JDialogCategorias.class.getName()).log(Level.SEVERE, null, ex);
			}
			try {
				preencher();
			} catch (DAOException ex) {

			}

		}
    }//GEN-LAST:event_jListCategoriasMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jListCategorias;
    private javax.swing.JMenuItem jMenuItemAdicionar;
    private javax.swing.JPopupMenu jPopupMenuCategorias;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
