/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.DAOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.NegocioException;
import negocio.pojos.Leilao;

/**
 *
 * @author Marnei
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private LeilaoControlador controlador;

    /**
     * Creates new form JanelaPrincipal
     *
     */
    public JFramePrincipal() {
        try {
            controlador = new LeilaoControlador();
        } catch (GuiException | DAOException | NegocioException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        preencherCampos();
    }

    public void preencherCampos() {
        preencherTabela();
        if (controlador.usuarioLogado != null) {
            this.setTitle("Leilão - Logado como " + controlador.usuarioLogado.getNome());
            jMenuItemLogin.setVisible(false);
            jMenuItemLogout.setVisible(true);
            jMenuUsuario.setVisible(true);
            jPanelAcoesLeilao.setVisible(true);
            if (controlador.usuarioLogado.getNome().equals("Administrador")) {
                jMenuAdmin.setVisible(true);
            }

        } else {
            this.setTitle("Leilão");
            jMenuItemLogin.setVisible(true);
            jMenuItemLogout.setVisible(false);
            jMenuUsuario.setVisible(false);
            jMenuAdmin.setVisible(false);
            jPanelAcoesLeilao.setVisible(false);
        }
    }

    public void preencherTabela() {
        try {
            ArrayList dados = new ArrayList();
            String[] colunas = new String[]{"Código", "Usuário", "Início", "Término", "Natureza", "Forma de lance"};
            List<Leilao> listaLeiloesEmAndamento = controlador.listarLeiloesEmAndamento();
            for (Leilao item : listaLeiloesEmAndamento) {
                dados.add(new Object[]{item.getCodigo(),
                    item.getUsuario().getNome(),
                    item.getDataInicio() + " " + item.getHoraInicio(),
                    item.getDataTermino() + " " + item.getHoraTermino(),
                    item.getNatureza().toString(),
                    item.getFormaLance().toString()});
            }
            LeilaoModelTable modeloTabelaLeiloesEmAndamento = new LeilaoModelTable(dados, colunas);
            jTableLeiloes.setModel(modeloTabelaLeiloesEmAndamento);
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuLeiloes = new javax.swing.JPopupMenu();
        jMenuItem = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLeiloes = new javax.swing.JTable();
        jPanelAcoesLeilao = new javax.swing.JPanel();
        jButtonAbrirLeilao = new javax.swing.JButton();
        jButtonAdicionarLeilao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemBDConfiguracoes = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBDCriar = new javax.swing.JMenuItem();
        jMenuItemBdRecriar = new javax.swing.JMenuItem();
        jMenuItemBDPopular = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuarioAtualizar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLeiloesListarMeus = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemCategorias = new javax.swing.JMenuItem();

        jMenuItem.setText("jMenuItem1");
        jPopupMenuLeiloes.add(jMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leilão");
        setName("framePrincipal"); // NOI18N

        jLabel1.setText("Leilões em andamento:");

        jTableLeiloes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableLeiloes);

        jButtonAbrirLeilao.setText("Abrir selecionado...");
        jButtonAbrirLeilao.setPreferredSize(new java.awt.Dimension(150, 23));

        jButtonAdicionarLeilao.setText("Adicionar...");
        jButtonAdicionarLeilao.setPreferredSize(new java.awt.Dimension(150, 23));
        jButtonAdicionarLeilao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarLeilaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcoesLeilaoLayout = new javax.swing.GroupLayout(jPanelAcoesLeilao);
        jPanelAcoesLeilao.setLayout(jPanelAcoesLeilaoLayout);
        jPanelAcoesLeilaoLayout.setHorizontalGroup(
            jPanelAcoesLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLeilaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdicionarLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAbrirLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAcoesLeilaoLayout.setVerticalGroup(
            jPanelAcoesLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcoesLeilaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonAbrirLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAdicionarLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Arquivo");

        jMenuItemLogin.setText("Login...");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogout);
        jMenu1.add(jSeparator1);

        jMenu2.setText("Configurações");

        jMenuItemBDConfiguracoes.setText("Conexão com o banco de dados...");
        jMenuItemBDConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDConfiguracoesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBDConfiguracoes);
        jMenu2.add(jSeparator3);

        jMenuItemBDCriar.setText("Criar banco da dados");
        jMenuItemBDCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDCriarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBDCriar);

        jMenuItemBdRecriar.setText("Recriar banco da dados");
        jMenuItemBdRecriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBdRecriarActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBdRecriar);

        jMenuItemBDPopular.setText("Popular banco de dados");
        jMenuItemBDPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDPopularActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBDPopular);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator4);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenuUsuario.setText("Meu perfil");

        jMenuItemUsuarioAtualizar.setText("Atualizar meus dados...");
        jMenuItemUsuarioAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioAtualizarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioAtualizar);
        jMenuUsuario.add(jSeparator2);

        jMenuItemLeiloesListarMeus.setText("Meus leilões...");
        jMenuItemLeiloesListarMeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLeiloesListarMeusActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemLeiloesListarMeus);

        jMenuBar1.add(jMenuUsuario);

        jMenuAdmin.setText("Administrativo");

        jMenuItemCategorias.setText("Categorias...");
        jMenuItemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriasActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemCategorias);

        jMenuBar1.add(jMenuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanelAcoesLeilao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAcoesLeilao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemBDConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDConfiguracoesActionPerformed
        new JFrameBdConfiguracoes().setVisible(true);
    }//GEN-LAST:event_jMenuItemBDConfiguracoesActionPerformed

    private void jMenuItemBDCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDCriarActionPerformed
        try {
            controlador.criarBD();
            JOptionPane.showMessageDialog(null, "O banco de dados foi criado com sucesso.", "Operação em banco de dados", JOptionPane.INFORMATION_MESSAGE);
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(
                    null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemBDCriarActionPerformed

    private void jMenuItemBdRecriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBdRecriarActionPerformed
        try {
            controlador.recriarBD();
            JOptionPane.showMessageDialog(null, "O banco de dados foi recriado com sucesso.", "Operação em banco de dados", JOptionPane.INFORMATION_MESSAGE);
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(
                    null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemBdRecriarActionPerformed

    private void jMenuItemBDPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDPopularActionPerformed
        try {
            controlador.popularBD();
            JOptionPane.showMessageDialog(null, "O banco de dados foi populado com sucesso.", "Operação em banco de dados", JOptionPane.INFORMATION_MESSAGE);
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(
                    null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemBDPopularActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        //new JFrameLogin().setVisible(true);
        JDialogLogin login = new JDialogLogin(this, true, controlador);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriasActionPerformed
        try {
            JDialogCategorias cat = new JDialogCategorias(this, true, controlador);
            cat.setVisible(true);

        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(
                    null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemCategoriasActionPerformed

    private void jMenuItemLeiloesListarMeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLeiloesListarMeusActionPerformed
        try {
            controlador.listarMeusLeiloes();

        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(
                    null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemLeiloesListarMeusActionPerformed

    private void jMenuItemUsuarioAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioAtualizarActionPerformed
        JDialogUsuario login = new JDialogUsuario(this, true, controlador, controlador.usuarioLogado);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioAtualizarActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        controlador.usuarioLogado = null;
        preencherCampos();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jButtonAdicionarLeilaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarLeilaoActionPerformed
        try {
            JDialogLeilao leilao = new JDialogLeilao(this, true, controlador, null);
            leilao.setVisible(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(
                    null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAdicionarLeilaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirLeilao;
    private javax.swing.JButton jButtonAdicionarLeilao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuItemBDConfiguracoes;
    private javax.swing.JMenuItem jMenuItemBDCriar;
    private javax.swing.JMenuItem jMenuItemBDPopular;
    private javax.swing.JMenuItem jMenuItemBdRecriar;
    private javax.swing.JMenuItem jMenuItemCategorias;
    private javax.swing.JMenuItem jMenuItemLeiloesListarMeus;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarioAtualizar;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanelAcoesLeilao;
    private javax.swing.JPopupMenu jPopupMenuLeiloes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTable jTableLeiloes;
    // End of variables declaration//GEN-END:variables

}
