/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dados.DAOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import negocio.NegocioException;

/**
 *
 * @author Marnei
 */
public class JFramePrincipal extends javax.swing.JFrame {

	private LeilaoControlador controlador;

	/**
	 * Creates new form JanelaPrincipal
	 *
	 */
	public JFramePrincipal() {
		try {
			controlador = new LeilaoControlador();
		} catch (GuiException | DAOException | NegocioException ex) {
			Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}
		//setExtendedState(JFrame.MAXIMIZED_BOTH);
		initComponents();
		jMenuUsuario.setVisible(false);
		jMenuAdmin.setVisible(false);
		jMenuItemLogout.setVisible(false);
	}

	public void preencherCampos() {
		if (controlador.usuarioLogado != null) {
			jMenuItemLogin.setVisible(false);
			jMenuItemLogout.setVisible(true);
			this.setTitle("Leilão - Logado como " + controlador.usuarioLogado.getNome());
			jMenuUsuario.setVisible(true);
			if (controlador.usuarioLogado.getNome().equals("Administrador")) {
				jMenuAdmin.setVisible(true);
			}
		} else {
			jMenuItemLogin.setVisible(true);
			jMenuItemLogout.setVisible(false);
			jMenuUsuario.setVisible(false);
			jMenuAdmin.setVisible(false);
			this.setTitle("Leilão");
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBDConfiguracoes = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuarioAtualizar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemLeiloesListarMeus = new javax.swing.JMenuItem();
        jMenuLeiloes = new javax.swing.JMenu();
        jMenuItemLeiloesListar = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuBancoDados = new javax.swing.JMenu();
        jMenuItemBDCriar = new javax.swing.JMenuItem();
        jMenuItemBDPopular = new javax.swing.JMenuItem();
        jMenuItemBdRecriar = new javax.swing.JMenuItem();
        jMenuItemCategorias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leilão");
        setName("framePrincipal"); // NOI18N

        jMenu1.setText("Arquivo");

        jMenuItemLogin.setText("Login...");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogout);
        jMenu1.add(jSeparator1);

        jMenuItemBDConfiguracoes.setText("Configurações...");
        jMenuItemBDConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDConfiguracoesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemBDConfiguracoes);
        jMenu1.add(jSeparator4);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSair);

        jMenuBar1.add(jMenu1);

        jMenuUsuario.setText("Meu perfil");

        jMenuItemUsuarioAtualizar.setText("Atualizar meus dados...");
        jMenuItemUsuarioAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioAtualizarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioAtualizar);
        jMenuUsuario.add(jSeparator2);

        jMenuItemLeiloesListarMeus.setText("Meus leilões...");
        jMenuItemLeiloesListarMeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLeiloesListarMeusActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemLeiloesListarMeus);

        jMenuBar1.add(jMenuUsuario);

        jMenuLeiloes.setText("Leilões");

        jMenuItemLeiloesListar.setText("Leilões em andamento...");
        jMenuItemLeiloesListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLeiloesListarActionPerformed(evt);
            }
        });
        jMenuLeiloes.add(jMenuItemLeiloesListar);

        jMenuBar1.add(jMenuLeiloes);

        jMenuAdmin.setText("Administrativo");

        jMenuBancoDados.setText("Banco de dados");

        jMenuItemBDCriar.setText("Criar banco da dados");
        jMenuItemBDCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDCriarActionPerformed(evt);
            }
        });
        jMenuBancoDados.add(jMenuItemBDCriar);

        jMenuItemBDPopular.setText("Popular banco de dados");
        jMenuItemBDPopular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBDPopularActionPerformed(evt);
            }
        });
        jMenuBancoDados.add(jMenuItemBDPopular);

        jMenuItemBdRecriar.setText("Recriar banco da dados");
        jMenuItemBdRecriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBdRecriarActionPerformed(evt);
            }
        });
        jMenuBancoDados.add(jMenuItemBdRecriar);

        jMenuAdmin.add(jMenuBancoDados);

        jMenuItemCategorias.setText("Categorias...");
        jMenuItemCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriasActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemCategorias);

        jMenuBar1.add(jMenuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
		System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemBDConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDConfiguracoesActionPerformed
		new JFrameBdConfiguracoes().setVisible(true);
    }//GEN-LAST:event_jMenuItemBDConfiguracoesActionPerformed

    private void jMenuItemBDCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDCriarActionPerformed
		try {
			controlador.criarBD();
			JOptionPane.showMessageDialog(null, "O banco de dados foi criado com sucesso.", "Operação em banco de dados", JOptionPane.INFORMATION_MESSAGE);
		} catch (DAOException ex) {
			Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}

    }//GEN-LAST:event_jMenuItemBDCriarActionPerformed

    private void jMenuItemBdRecriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBdRecriarActionPerformed
		try {
			controlador.recriarBD();
			JOptionPane.showMessageDialog(null, "O banco de dados foi recriado com sucesso.", "Operação em banco de dados", JOptionPane.INFORMATION_MESSAGE);
		} catch (DAOException ex) {
			Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_jMenuItemBdRecriarActionPerformed

    private void jMenuItemBDPopularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBDPopularActionPerformed
		try {
			controlador.popularBD();
			JOptionPane.showMessageDialog(null, "O banco de dados foi populado com sucesso.", "Operação em banco de dados", JOptionPane.INFORMATION_MESSAGE);
		} catch (DAOException ex) {
			Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_jMenuItemBDPopularActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
		//new JFrameLogin().setVisible(true);
		JDialogLogin login = new JDialogLogin(this, true, controlador);
		login.setVisible(true);
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    private void jMenuItemCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriasActionPerformed
		try {
			JDialogCategorias cat = new JDialogCategorias(this, true, controlador);
			cat.setVisible(true);
		} catch (DAOException ex) {
			Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
		}
    }//GEN-LAST:event_jMenuItemCategoriasActionPerformed

    private void jMenuItemLeiloesListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLeiloesListarActionPerformed
		controlador.listarLeiloesEmAndamento();
    }//GEN-LAST:event_jMenuItemLeiloesListarActionPerformed

    private void jMenuItemLeiloesListarMeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLeiloesListarMeusActionPerformed
		try {
			controlador.listarMeusLeiloes();
		} catch (DAOException ex) {
			Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_jMenuItemLeiloesListarMeusActionPerformed

    private void jMenuItemUsuarioAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioAtualizarActionPerformed
		JDialogUsuario login = new JDialogUsuario(this, true, controlador, controlador.usuarioLogado);
		login.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioAtualizarActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        controlador.usuarioLogado = null;
		preencherCampos();
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new JFramePrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenu jMenuBancoDados;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBDConfiguracoes;
    private javax.swing.JMenuItem jMenuItemBDCriar;
    private javax.swing.JMenuItem jMenuItemBDPopular;
    private javax.swing.JMenuItem jMenuItemBdRecriar;
    private javax.swing.JMenuItem jMenuItemCategorias;
    private javax.swing.JMenuItem jMenuItemLeiloesListar;
    private javax.swing.JMenuItem jMenuItemLeiloesListarMeus;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemUsuarioAtualizar;
    private javax.swing.JMenu jMenuLeiloes;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables

}
